### ISSUE TITLE
Use XDG locations for configuration

### ISSUE THREAD

**Issue by SISheogorath** [eliran89c/klama#12]
Instead of filling the home directory with dotfiles, it would be amazing, if you could utilise the freedesktop standard config locations: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

In this particular case `XDG_CONFIG_HOME` to store the configuration.

**Comment by eliran89c** [comment]
> Instead of filling the home directory with dotfiles, it would be amazing, if you could utilise the freedesktop standard config locations: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> 
> In this particular case `XDG_CONFIG_HOME` to store the configuration.

Hi @SISheogorath 
Thank you for the suggestion! I agree, adopting the XDG specification is a great idea. I've added this to my project backlog and will work on implementing it soon.​​​​​​​​​​​​​​​​
